- name: creando "sysctl.d/k8s.conf"
  shell:
        cmd: |
          cat > /etc/sysctl.d/k8s.conf << EOF
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
  become: yes

- name: recargamos sysctl
  command: "sysctl --system"
  become: yes


- name: desactivamos swap
  command: "swapoff  -a"
  become: yes

- name: Eliminamos swap
  lineinfile:
          path: /etc/fstab
          regexp: "swap" 
          state: absent
          backup: yes
  become: yes
