
- name: Añadiendo reglas para permitir la red docker de los nodos
  command: "firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address={{ ansible_docker0.ipv4.address }}/16  accept'"
  when:  "'workers' in group_names"
  delegate_to: master.azure  
  become: true



- name: Añadiendo reglas para permitir la red  de los nodos
  command: "firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address={{ ansible_default_ipv4.address }}/32  accept'"
  when:  "'workers' in group_names"
  delegate_to: master.azure
  become: true


- name: reload firewalld
  command: "firewall-cmd --reload"
  become: true
  delegate_to: master.azure
