- name: Aplicando reglas de firewall 
  firewalld:
    port: "{{item}}"
    permanent: yes
    state: enabled
  with_items:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
    - 10255/tcp
  become: yes

- name: Recargamos reglas firewall 
  command: firewall-cmd --reload
  become: yes
